# Argo CD Application for ROSA Regional Frontend
#
# This application deploys the rosa-regional-frontend using a Helm chart
# that dynamically reads configuration from the aws-lbc-cluster-config
# ConfigMap in kube-system namespace using Helm's lookup function.
#
# Prerequisites:
#   - aws-lbc-cluster-config ConfigMap must exist in kube-system namespace
#   - ConfigMap should contain:
#       - region: AWS region
#       - cluster-name: EKS cluster name
#       - vpc-id: VPC ID
#       - api-target-group-arn: Target Group ARN for the API
#       - role-arn: IAM role ARN
#
# Usage:
#   kubectl apply -f argocd/rosa-regional-frontend/application.yaml
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rosa-regional-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: rosa-regional-frontend
    app.kubernetes.io/part-of: rosa-regional-frontend
spec:
  project: default

  source:
    repoURL: https://github.com/openshift-online/rosa-regional-frontend-api.git
    targetRevision: main
    path: deployment/helm/rosa-regional-frontend

    helm:
      releaseName: rosa-regional-frontend
      valueFiles:
        - values.yaml

      parameters:
        - name: config.dynamodb.tableName
          value: "rosa-customer-accounts"
        - name: config.maestroUrl
          value: "http://maestro-server:8000"
        - name: config.logLevel
          value: "info"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: rosa-regional-frontend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m