apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hyperfleetAdapter1Chart.applicationName }}-manifestwork
  namespace: {{ .Values.hyperfleetAdapter1Chart.targetNamespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.hyperfleetAdapter1Chart.applicationName }}
    app.kubernetes.io/component: manifestwork
data:
  manifestwork.yaml: |
{{ .Files.Get "manifestwork.yaml" | nindent 4 }}
